# Generated by Django 2.2.16 on 2020-09-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_pacote_inscicoe_papeis_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('carga_horaria', models.CharField(max_length=45)),
                ('data', models.DateTimeField()),
                ('horario_inicio', models.DateTimeField()),
                ('horario_termino', models.DateTimeField()),
                ('valor_inscricao', models.DecimalField(decimal_places=15, max_digits=45)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
    ]
