# Generated by Django 2.2.16 on 2020-09-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=45)),
                ('valor', models.CharField(max_length=45)),
                ('pacote_inscicoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Pacote_Inscicoe')),
            ],
        ),
        migrations.CreateModel(
            name='Ministrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('curriculo', models.TextField(max_length=400)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
                ('pacote_inscicoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Pacote_Inscicoe')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Usuario')),
            ],
        ),
    ]
